### ISSUE TITLE
mod_rewrite rule to disallow access to file extensions is invalid

### ISSUE THREAD

**Issue by madmatt** [silverstripe/cwp-installer#21]
The `RewriteRule` in public/assets/.htaccess doesn't work correctly when there are multiple fullstops in the filename. The offending line is https://github.com/silverstripe/cwp-installer/blob/master/public/assets/.htaccess#L28.

For example: `assets/abc123/test.jpg` works, but `assets/abc123/test.v2.jpg` doesn't match.

I wrote a quick and dirty update to it, but haven't tested this extensively:

```
# Block invalid file extensions
RewriteCond %{REQUEST_URI} !\.[^.]*(?i:css|js|ace|arc|arj|asf|au|avi|bmp|bz2|cab|cda|csv|dmg|doc|docx|dotx|flv|gif|gpx|gz|hqx|ico|jpeg|jpg|kml|m4a|m4v|mid|midi|mkv|mov|mp3|mp4|mpa|mpeg|mpg|ogg|ogv|pages|pcx|pdf|png|pps|ppt|pptx|potx|ra|ram|rm|rtf|sit|sitx|tar|tgz|tif|tiff|txt|wav|webm|wma|wmv|xls|xlsx|xltx|zip|zipx|graphql)$
RewriteRule .* - [F]```

**Comment by robbieaverill** [comment]
Cheers @madmatt, we're tracking this at the moment in https://github.com/silverstripe/silverstripe-assets/issues/141
