### ISSUE TITLE
Remove subsites module as default functionality

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-installer#33]
## Overview
For new sites, where the development agency wants to use this package to kickstart their project, we shouldn't assume that the subsites module should be provided by default.

Given that subsites significantly impacts how the site can be maintained in the future, it is a decision that should be supported by conversations between the development agency and site owner and good documentation, e.g [CWP website (WIP)](https://www.cwp.govt.nz/developer-docs/en/2/features/multiple_sites) and the [module readme](https://github.com/silverstripe/silverstripe-subsites) where a number of limitations are noted.

This issue tracks removing the subsite module from the CWP installer for the next minor version.

## Pull request
Note, this is all I could see requiring a change so I've created the PR. I'd appreciate input in case other areas may need updating.

- [x] https://github.com/silverstripe/cwp-installer/pull/34

**Comment by michalkleiner** [comment]
👏 

Next one — taxonomy module.

**Comment by brynwhyman** [comment]
😆 Great to see some support @michalkleiner. Yup, fair call on the taxonomy module. What's your reasoning for removing this functionality from the base installer?

**Comment by michalkleiner** [comment]
Our reason is that we have a custom taxonomies module and we need to be hiding the SS module's model admin and the tag field from everywhere to avoid CMS user's confusion. The taxonomy module can still come in as a dependency of recipe-blog or added by agencies per project when required.

**Comment by brynwhyman** [comment]
Note that there is a follow-up issue for docs updates here: https://github.com/silverstripe/cwp/issues/272. That shouldn't block this issue and will happen before the next minor release.
