### ISSUE TITLE
Include MFA modules

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-installer#35]
## Overview

With the next minor release of CWP, the multi-factor authentication module suite should be included for all new sites built with the cwp-installer. 

### What's in the MFA module suite?
- [Silverstripe MFA](https://github.com/silverstripe/silverstripe-mfa)
- [TOTP](https://github.com/silverstripe/silverstripe-totp-authenticator)
- ~[Security token, via WebAuthn](https://github.com/silverstripe/silverstripe-webauthn-authenticator)~ [see comment below](https://github.com/silverstripe/cwp/issues/258#issuecomment-626443863)

### Acceptance Criteria

- Take the MFA and TOTP modules out of [kitchen-sink](https://github.com/silverstripe/cwp-recipe-kitchen-sink/blob/2/composer.json) (although leave the WebAuthn module
- The next minor release of CWP includes the following modules in the [cwp-installer](https://github.com/silverstripe/cwp-installer) module: [Silverstripe MFA](https://github.com/silverstripe/silverstripe-mfa) and [TOTP](https://github.com/silverstripe/silverstripe-totp-authenticator)
- The test for the MFA module are considered and placed in the appropriate module for CI, i.e stay in kitchen-sink and/or move to cwp-installer?
- ~The change log for the associated CWP release includes clear guidance on:~
  - ~What MFA functionality will be included~
  - ~Direct readers to documentation on getting the modules running on a local development environment~

### Notes
- More docs changes for this are covered here: https://github.com/silverstripe/cwp/issues/269

### Pull Requests
- [x] https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/67 remove MFA from kitchen sink
- [x] https://github.com/silverstripe/cwp-installer/pull/36 add MFA to installer
- [x] https://github.com/silverstripe/cwp/pull/275 changelog record for CWP

**Comment by brynwhyman** [comment]
I've moved this issue to the cwp-installer repository and update the description to focus on getting the modules added to this repo and some related changelog notes.

Other points around futher documentation will be captured in this issue: https://github.com/silverstripe/cwp/issues/269

**Comment by chillu** [comment]
> Do you have any ideas on how to ensure that Developers get the TOTP encryption key .env variable? 

Within the scope of CWP, it's a default on Revera, and hopefully soon a default on AWS. Until that point, I think we need to add something to https://www.cwp.govt.nz/developer-docs/en/2/getting_started/

**Comment by brynwhyman** [comment]
Alright, we'll have that covered in https://github.com/silverstripe/cwp/issues/269

**Comment by brynwhyman** [comment]
> The change log for the associated CWP release includes clear guidance on:

I think this AC can be removed, it's already covered in: https://github.com/silverstripe/cwp/issues/269
