### ISSUE TITLE
Enable projects to use a public webroot by default

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-installer#6]
Since CWP 2.0 will ship with SS core 4.1.x we will have the ability to implement a public webroot as the base for serving web requests:

* https://github.com/silverstripe/silverstripe-framework/issues/7419
* https://docs.silverstripe.org/en/4/changelogs/4.1.0/#upgrade-public-folder

We'll also need to add documentation to cwp/cwp to ensure that if users want to disable this they know how to.

**Comment by NightJar** [comment]
This recipe is already based from 4.1.x (via dev requirements to various other recipes), so I should imagine this issue to be more of a test to ensure functionality remains :)

**Comment by robbieaverill** [comment]
I don't think the public webroot feature is enabled by default, so this ticket is to enable it for CWP 2.0

**Comment by NightJar** [comment]
Seems to be, as I just installed the 4.1 dev branch via `silverstripe/installer` (in that it requires `silverstripe/recipe-cms`:`1.1.x-dev` same as here in #5 ) and it's running out of `public`.  That of course doesn't preclude something in `silverstripe/installer` specifically that is enabling this, so it's worth testing still :)

**Comment by robbieaverill** [comment]
Whoops - closed by accident

**Comment by NightJar** [comment]
Does the existing `public/` folder in this recipe not achieve the desired effect?
I will test.

**Comment by NightJar** [comment]
Tested, works :)
(as is, current `master`)

```sh
~/work/cwp2test (master)
$ ls
behat.yml  composer.json  composer.lock  gridfield-bulk-editing-tools/  mysite/  phpcs.xml.dist  phpunit.xml.dist  public/  README.md  robots.txt  themes/  vendor/

~/work/cwp2test (master)
$ ls public/
index.php  install.php  install-frameworkmissing.html  resources/  web.config
```

Thanks @tractorcow for the guidance.

**Comment by tractorcow** [comment]
Yep all good. Unlike other recipe files, the `public` folder needs to be in every recipe down the stack.
